{
 "title": "interfaces_counters",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "dev",
    "query": "SHOW TAG VALUES FROM \"ifcounters\" WITH KEY=\"device\""
   },
   {
    "name": "int",
    "query": "SHOW TAG VALUES FROM \"ifcounters\" WITH KEY=\"name\" WHERE \"device\"=~ /^$dev$/"
   }
  ]
 },
 "panels": [
  {
   "title": "pps - device $dev ",
   "type": "graph",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "alias": "out_unicast_pps all int",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ifcounters",
     "query": "SELECT derivative(sum(\"out_unicast_pkts\"), 1s) AS \"out_unicast_pps\" FROM \"ifcounters\" WHERE (\"device\" =~ /^$dev$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "in_unicast_pps all int",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ifcounters",
     "query": "SELECT derivative(sum(\"in_unicast_pkts\"), 1s) AS \"in_unicast_pps\" FROM \"ifcounters\" WHERE (\"device\" =~ /^$dev$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "total_unicast_pps all int",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ifcounters",
     "query": "SELECT derivative(sum(\"in_unicast_pkts\"), 1s)  + derivative(sum(\"out_unicast_pkts\"), 1s) AS total_unicast_pps FROM \"ifcounters\" WHERE (\"device\" =~ /^$dev$/) AND $timeFilter GROUP BY time($__interval) fill(null) ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "bps - device $dev - int $int",
   "type": "graph",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "in_bps",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ifcounters",
     "query": "SELECT derivative(mean(\"in_octets\"), 1s) FROM \"ifcounters\" WHERE (\"device\" = 'leaf-1' AND \"name\" = 'Ethernet1') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "in_octets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "in_bps" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$dev$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$int$/" }
     ]
    },
    {
     "alias": "out_bps",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ifcounters",
     "query": "SELECT derivative(mean(\"in_octets\"), 1s) FROM \"ifcounters\" WHERE (\"device\" = 'leaf-1' AND \"name\" = 'Ethernet1') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "out_octets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "out_bps" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$dev$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$int$/" }
     ]
    }
   ]
  },
  {
   "title": "unicast pps - device $dev - int $int",
   "type": "graph",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "alias": "in_unicast_pps",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ifcounters",
     "query": "SELECT derivative(mean(\"in_octets\"), 1s) FROM \"ifcounters\" WHERE (\"device\" = 'leaf-1' AND \"name\" = 'Ethernet1') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "in_unicast_pkts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "in_unicast_pps" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$dev$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$int$/" }
     ]
    },
    {
     "alias": "out_unicast_pps",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ifcounters",
     "query": "SELECT derivative(mean(\"in_octets\"), 1s) FROM \"ifcounters\" WHERE (\"device\" = 'leaf-1' AND \"name\" = 'Ethernet1') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "out_unicast_pkts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "out_unicast_pps" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$dev$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$int$/" }
     ]
    }
   ]
  },
  {
   "title": "bps - device $dev",
   "type": "graph",
   "gridPos": { "h": 9, "w": 23, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "in_bps $tag_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ifcounters",
     "query": "SELECT derivative(mean(\"in_octets\"), 1s) FROM \"ifcounters\" WHERE (\"device\" = 'leaf-1' AND \"name\" = 'Ethernet1') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "in_octets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "in_bps" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$dev$/" }
     ]
    },
    {
     "alias": "out_bps $tag_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ifcounters",
     "query": "SELECT derivative(mean(\"in_octets\"), 1s) FROM \"ifcounters\" WHERE (\"device\" = 'leaf-1' AND \"name\" = 'Ethernet1') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "out_octets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "out_bps" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$dev$/" }
     ]
    }
   ]
  },
  {
   "title": "unicast pps - device $dev",
   "type": "graph",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "alias": "in_unicast_pps $tag_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ifcounters",
     "query": "SELECT derivative(mean(\"in_octets\"), 1s) FROM \"ifcounters\" WHERE (\"device\" = 'leaf-1' AND \"name\" = 'Ethernet1') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "in_unicast_pkts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "in_unicast_pps" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$dev$/" }
     ]
    },
    {
     "alias": "out_unicast_pps $tag_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ifcounters",
     "query": "SELECT derivative(mean(\"in_octets\"), 1s) FROM \"ifcounters\" WHERE (\"device\" = 'leaf-1' AND \"name\" = 'Ethernet1') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "out_unicast_pkts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "out_unicast_pps" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$dev$/" }
     ]
    }
   ]
  },
  {
   "title": "stddev - leaf uplinks - out bps",
   "type": "graph",
   "description": "hardcoded query",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$dev",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ifcounters",
     "query": "SELECT derivative(stddev(\"out_octets\"), 1s)  / 8 FROM \"ifcounters\" WHERE (\"name\" =~ /Ethernet(1|2)/ AND \"device\" =~ /DC1-LEAF.*/) AND $timeFilter GROUP BY time($__interval), \"device\" fill(null)",
     "select": [
      [
       { "params": [ "out_octets" ], "type": "field" },
       {
        "params": [],
        "type": "stddev"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ " / 8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/Ethernet(1|2)/" },
      { "condition": "AND", "key": "device", "operator": "=~", "value": "/DC1-LEAF.*/" }
     ]
    }
   ]
  }
 ]
}