username: arista
password: arista
insecure: true
log-file: /tmp/gnmic.log
#address: 
#  - "10.73.1.105:6030"
#  - "10.73.1.106:6030"
port: 6030

targets:
  10.73.1.105: 
    subscriptions:
      - bgp
    outputs:
      - output1
  10.73.1.106: 
    subscriptions:
      - port_stats
    outputs:
      - output2

subscriptions:
  port_stats:
    paths:
      - "/interfaces/interface[name=Ethernet1]/state/counters"
    stream-mode: sample
    sample-interval: 10s
  bgp:
    paths:
      - "/network-instances/network-instance[name=default]/protocols/protocol/bgp/neighbors/neighbor[neighbor-address=192.168.255.2]/state/session-state"
    stream-mode: on-change
    heartbeat-interval: 10s
outputs:
  output1:
    type: file
    filename: ./gnmi_output.txt
    format: event
    event-processors:
      - ts_processor

processors:
  ts_processor:
    event-override-ts:
      precision: ms
