fabric_name: orange

output_format:
  - text
  - markdown
  - json
  - yaml

commands_list:
  - show lldp neighbors
  - show ip interface brief
  - show interfaces description
  - show version
  - show running-config

